// <auto-generated />
using System;
using IS.DbCommon;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IS.DbCommon.Migrations
{
    [DbContext(typeof(ImageServerEFContext))]
    partial class ImageServerEFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IS.DbCommon.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("IS.DbCommon.Models.Face", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("bytea");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.Property<int>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PhotoId");

                    b.ToTable("faces", (string)null);
                });

            modelBuilder.Entity("IS.DbCommon.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FaceCount")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.PrimitiveCollection<string[]>("Labels")
                        .HasColumnType("text[]");

                    b.Property<string>("PerceptualHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("PostedByAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("PostedByAccountId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("IS.DbCommon.Models.Metadata", b =>
                {
                    b.Property<int>("PhotoId")
                        .HasColumnType("integer");

                    b.Property<string>("AiMetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("CameraMake")
                        .HasColumnType("text");

                    b.Property<string>("CameraModel")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExifRawJson")
                        .HasColumnType("text");

                    b.Property<string>("ExposureTime")
                        .HasColumnType("text");

                    b.Property<string>("Extension")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<float?>("FNumber")
                        .HasColumnType("real");

                    b.Property<int>("FacesDetected")
                        .HasColumnType("integer");

                    b.Property<bool>("FacesScanned")
                        .HasColumnType("boolean");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool?>("FlashFired")
                        .HasColumnType("boolean");

                    b.Property<float?>("FocalLengthMm")
                        .HasColumnType("real");

                    b.Property<double?>("GpsAltitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpsLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("GpsLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("HashSha1")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("Iso")
                        .HasColumnType("integer");

                    b.Property<string>("LensModel")
                        .HasColumnType("text");

                    b.Property<string>("LocationCity")
                        .HasColumnType("text");

                    b.Property<string>("LocationCountry")
                        .HasColumnType("text");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<short?>("Orientation")
                        .HasColumnType("smallint");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("PhotoId");

                    b.ToTable("photo_metadata", (string)null);
                });

            modelBuilder.Entity("IS.DbCommon.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("FaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("FaceId")
                        .IsUnique();

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("IS.DbCommon.Models.Face", b =>
                {
                    b.HasOne("IS.DbCommon.Models.Person", "Person")
                        .WithMany("Faces")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IS.DbCommon.Models.Image", "Photo")
                        .WithMany("Faces")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("IS.DbCommon.Models.Image", b =>
                {
                    b.HasOne("IS.DbCommon.Models.Account", "PostedByAccount")
                        .WithMany("PostedImages")
                        .HasForeignKey("PostedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PostedByAccount");
                });

            modelBuilder.Entity("IS.DbCommon.Models.Metadata", b =>
                {
                    b.HasOne("IS.DbCommon.Models.Image", "Image")
                        .WithOne("Metadata")
                        .HasForeignKey("IS.DbCommon.Models.Metadata", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("IS.DbCommon.Models.Person", b =>
                {
                    b.HasOne("IS.DbCommon.Models.Account", "Account")
                        .WithOne("Person")
                        .HasForeignKey("IS.DbCommon.Models.Person", "AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IS.DbCommon.Models.Face", "MainFace")
                        .WithOne()
                        .HasForeignKey("IS.DbCommon.Models.Person", "FaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");

                    b.Navigation("MainFace");
                });

            modelBuilder.Entity("IS.DbCommon.Models.Account", b =>
                {
                    b.Navigation("Person");

                    b.Navigation("PostedImages");
                });

            modelBuilder.Entity("IS.DbCommon.Models.Image", b =>
                {
                    b.Navigation("Faces");

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("IS.DbCommon.Models.Person", b =>
                {
                    b.Navigation("Faces");
                });
#pragma warning restore 612, 618
        }
    }
}
